### ISSUE TITLE
[META] Plugin + Forge client mod list

### ISSUE THREAD

**Issue by CruzBishop** [Techern/Netherrack#2]
This is a list of plugins and Forge client mods that will be added as either examples or for actual use.
### Forge + Netherrack (combination)
- [ ] Netherrack core client mod: A few extra packets to make everything easier, but not required. Just recommended. 
- [ ] Reworked paintings to make for much easier decoration and the ability to allow clients to download new paintings from the server
- [ ] Rewrite of Igneous Additions as Netherrack exclusive
  More to be added later
